# Generated by Django 6.1 on 2026-08-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.ManyToManyField(to='News_app.tag'),
        ),
    ]
