# Generated by Django 6.1 on 2026-08-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_app', '0002_tag_news_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='news/news-bg-3.jpg', upload_to='news/'),
        ),
    ]
