# Generated by Django 6.1 on 2026-08-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_app', '0003_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='news/default.jpg', upload_to='news/'),
        ),
    ]
