# Generated by Django 6.1 on 2026-08-12 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discription',
        ),
    ]
