# Generated by Django 6.1 on 2026-08-19 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_app', '0005_order_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending ...'), ('paid', 'Paid =]'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled =(')], default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending ...'), ('paid', 'Paid =]'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled =(')], max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_data', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Shop_app.order')),
            ],
        ),
    ]
