# Generated by Django 6.1 on 2026-08-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_app', '0006_alter_order_status_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending ...'), ('paid', 'Paid =]'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled =(')], default='pending', max_length=50),
        ),
    ]
