# Generated by Django 6.1 on 2026-08-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop_app', '0011_order_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending ...'), ('paid', 'Paid =]'), ('shipped', 'Shipped'), ('expride', 'Expride'), ('cancelled', 'Cancelled =(')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending ...'), ('paid', 'Paid =]'), ('shipped', 'Shipped'), ('expride', 'Expride'), ('cancelled', 'Cancelled =(')], default='pending', max_length=50),
        ),
    ]
